Added english translation for 'UIWebView and VIPER' chapter
strongself/The-Book-of-VIPER pull request #40
Opened 2016-10-01 17:44 UTC by BNTR

Ну и в догонку перевод на перевод главы 'UIWebView and VIPER'. Буду рад если помогу этим)

2016-10-07 06:29 UTC, etolstoy commented
Спасибо за перевод, но проблем с ним очень много, в таком виде сливать не готовы. На самом деле, материал для этой главы я взял из [статьи](http://etolstoy.com/2016/02/28/viper-webview/) в своем же блоге, так что можно спокойно ее использовать в качестве сырого материала для подготовки перевода.

2016-10-08 20:57 UTC, BNTR commented
Обновил перевод, используя твою статью. Дайте знать если еще что-то поправить нужно будет =)

2016-10-14 21:40 UTC, etolstoy requested changes

2016-10-14 21:40 UTC, etolstoy commented on english/webview.md
> +The fundamental idea - separate `UIWebView` responsibilities in two groups: `WebEngine`, which is a dependency of the Interactor, and `WebPresentation` which belongs to the View.
> idea - separate

idea is to separate

2016-10-14 21:40 UTC, etolstoy commented on english/webview.md
> +- Executes JavaScript scripts.
Думаю, *scripts* можно опустить

2016-10-14 21:40 UTC, etolstoy commented on english/webview.md
> +2. The Presenter (or View in case of cell) is an entry point of the module. It's only input is raw html data.
**the** View, **a** cell.

2016-10-14 21:46 UTC, BNTR commented
Поправил.

2016-10-14 21:46 UTC, etolstoy commented
Огонь, спасибо! :)

2016-10-14 21:46 UTC, merged